<!DOCTYPE html>
<html>
<head>
<base href="http://dkolf.de/src/dkjson-lua.fsl/artifact" />
<title>Artifact Content - dkjson</title>
<link rel="alternate" type="application/rss+xml" title="RSS Feed"
      href="/src/dkjson-lua.fsl/timeline.rss" />
<link rel="stylesheet" href="/src/dkjson-lua.fsl/style.css?default" type="text/css"
      media="screen" />
</head>
<body>
  <h1>Artifact Content &mdash; dkjson</h1>
<div class="mainmenu">
<a href='/'>dkolf.de</a>
<a href='/src/dkjson-lua.fsl/home'>dkjson</a>
<a href='/src/dkjson-lua.fsl/timeline'>Timeline</a>
<a href='/src/dkjson-lua.fsl/brlist'>Branches</a>
<a href='/src/dkjson-lua.fsl/taglist'>Tags</a>
<a href='/src/dkjson-lua.fsl/wiki'>Wiki</a>
<a href='/src/dkjson-lua.fsl/login'>Login</a>
</div>
<div class="submenu">
<a class="label" href="/src/dkjson-lua.fsl/timeline?n=200&amp;uf=f1093c6b2e5a858b6100958c8c5e575ae439a0df">Checkins Using</a>
<a class="label" href="/src/dkjson-lua.fsl/raw/dkjson-2.5-2.rockspec?name=f1093c6b2e5a858b6100958c8c5e575ae439a0df">Download</a>
<a class="label" href="/src/dkjson-lua.fsl/hexdump?name=f1093c6b2e5a858b6100958c8c5e575ae439a0df">Hex</a>
</div>
<div class="content">
<script>
function gebi(x){
if(/^#/.test(x)) x = x.substr(1);
var e = document.getElementById(x);
if(!e) throw new Error("Expecting element with ID "+x);
else return e;}
</script>
<h2>Artifact f1093c6b2e5a858b6100958c8c5e575ae439a0df:</h2>
<ul>
<li>File
<a id='a1' href='/src/dkjson-lua.fsl/honeypot'>dkjson-2.5-2.rockspec</a>
<ul>
<li>
2015-03-02 20:42:23
- part of checkin
<span class="timelineHistDsp">[dbf5178674]</span>
on branch <a id='a2' href='/src/dkjson-lua.fsl/honeypot'>trunk</a>
- tested for Lua 5.3, updated rockspec
 (user:
dhkolf
</ul>
</ul>
<hr />
<blockquote>
<pre>
package = &quot;dkjson&quot;
version = &quot;2.5-2&quot;
source = {
  url = &quot;http://dkolf.de/src/dkjson-lua.fsl/tarball/dkjson-2.5.tar.gz?uuid=release_2_5&quot;,
  file = &quot;dkjson-2.5.tar.gz&quot;
}
description = {
  summary = &quot;David Kolf's JSON module for Lua&quot;,
  detailed = [[
dkjson is a module for encoding and decoding JSON data. It supports UTF-8.

JSON (JavaScript Object Notation) is a format for serializing data based
on the syntax for JavaScript data structures.

dkjson is written in Lua without any dependencies, but
when LPeg is available dkjson uses it to speed up decoding.
]],
  homepage = &quot;http://dkolf.de/src/dkjson-lua.fsl/&quot;,
  license = &quot;MIT/X11&quot;
}
dependencies = {
  &quot;lua &gt;= 5.1, &lt; 5.4&quot;
}
build = {
  type = &quot;builtin&quot;,
  modules = {
    dkjson = &quot;dkjson.lua&quot;
  }
}


</pre>
</blockquote>
</div>
<div class="footer">
  <a href="./">dkolf.de</a>
  <a href="/contact">contact</a>
  (This page was generated by <a class="extlink" href="http://www.fossil-scm.org/">Fossil</a>.)
</div>
</body></html>
